-- ########################## CREATE TABLE SQL STATEMENTS ##########################
-- Main Entities
CREATE TABLE Users ( 
 UID VARCHAR(10) PRIMARY KEY, 
 password VARCHAR(30) NOT NULL, 
 userType VARCHAR(1) NOT NULL,
 sessionGeo VARCHAR(30) NOT NULL,
 sessionIP VARCHAR(45) NOT NULL
) ENGINE=InnoDB;


CREATE TABLE RegisteredUsers ( 
 UID VARCHAR(10) PRIMARY KEY,
 email VARCHAR(50) NOT NULL,
 userName VARCHAR(50) NOT NULL,
 userRank VARCHAR(5) NOT NULL,

 FOREIGN KEY (UID) REFERENCES Users(UID)
) ENGINE=InnoDB;

CREATE TABLE Questions(
 QID VARCHAR(10) PRIMARY KEY,
 UID VARCHAR(10) NOT NULL,
 title VARCHAR(140) NOT NULL,
 _timestamp VARCHAR(20) NOT NULL,
 numRating VARCHAR(5) NOT NULL,
 content VARCHAR(1000) NOT NULL,
 category VARCHAR(2) NOt NULL,
 location VARCHAR(30) NOT NULL,

 FOREIGN KEY (UID) REFERENCES Users(UID)
) ENGINE=InnoDB;

CREATE TABLE Answers(
 AID VARCHAR(10) NOT NULL,
 QID VARCHAR(10) NOT NULL,
 UID VARCHAR(10) NOT NULL,
 _timestamp VARCHAR(20) NOT NULL,
 numRating VARCHAR(5) NOT NULL,
 content VARCHAR(1000) NOT NULL,
 
 PRIMARY KEY(QID,AID),
 FOREIGN KEY (UID) REFERENCES RegisteredUsers(UID),
 FOREIGN KEY (QID) REFERENCES Questions(QID)
) ENGINE=InnoDB;
